### ISSUE TITLE
Export to HTML button in document properties

### ISSUE THREAD

**Issue by ewuerger** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter#116]
## Mandatory
An additional button below `Export to PDF` with an HTML icon (just like PDF icon but with HTML text) in the Document Properties navigation bar, that downloads the produced HTML page that is passed to Weasyprint.

## Optional
Extend the REST API with an endpoint for just HTML processing.

### Motivation

Hello dear Polarion PDF Exporter plugin devs,

first of all great work with the plugin! 

When we want to work on the style package of the plugin (CSS style-sheet, cover page,...) it is sometimes hard to figure out what the correct CSS rules are, and if we need !important because there are already inline styles on the HTML elements. The HTML structure is very important to be known in order to come up with correct CSS styling rules. Also this helps the user to understand some processing that the plugin does, e.g. work item tables. When a user doesn't have access to the server where Polarion runs, she can't access the produced HTML that is passed to Weasyprint. 

It would help very much to be able to receive this HTML from the frontend and I think this shouldn't mean too much implementation work.  

This would help us immensely to style the produced PDFs via CSS rules.

Cheers

**Comment by ralfsmolarek3** [comment]
Hello @ewuerger ,
thanks for the request. Adding this to the REST API makes sense to me. Let me check. Adding a button I personally do not really like but I understand where you are coming from!

**Comment by grigoriev** [comment]
Hi @ewuerger,

after some discussions we decided that such a button on the UI would be a bit redundant for such purposes. 
So we simply added a REST API endpoint:
<img width="990" alt="image" src="https://github.com/user-attachments/assets/4613e7ee-2138-4d14-a6ef-5afa673f09ad">

It's similar to `/api/convert`endpoint, but returns desired HTML instead of producing PDF.

Please let us know if it's not sufficient or in case of any findings/bugs.

**Comment by ewuerger** [comment]
I will test this next week. Thank you very much! @grigoriev @ralfsmolarek3
