### ISSUE TITLE
PDF job disappears after completion

### ISSUE THREAD

**Issue by schlami** [SchweizerischeBundesbahnen/ch.sbb.polarion.extension.pdf-exporter#172]
### Current Behavior

I'm using const url = 'http://polarion/polarion/pdf-exporter/rest/api/convert/jobs/' + pdfID; to check whether the PDF job has been successfully completed. As long as the job is running, I get code 202 as response, which is ok. As soon as the job finishes, I receive code 200 (instead of 303) and the job disappears. All following requests response with code 404 (no job available). Is this an intended behaviour? The same happens if I use Swagger. HAs this been fixed in later releases of the extension?

### Expected Behavior

see above

### Steps To Reproduce

see above

### Environment - OS

Linux

### Polarion version

2404

### Extension Version

5.5.4

**Comment by nirikash** [comment]
Yes, this behavior is intended in order to avoid the accumulation of tons of successfully finished jobs with converted pdfs.
After the first successful job result query, if job is finished, it will be deleted.
For failed jobs there is configurable timeout in pdf-converter-jobs.properties (jobs.timeout.finished.minutes=30)

I can imagine to extend this timeout for successfully finished jobs as well to preserve converted pdf for specified time.

**Comment by nirikash** [comment]
I think I know what happens: you receive 303 from GET /convert/jobs/{id} with Location response header /convert/jobs/{id}/result. And your browser is imediately **automatically** redirected to /convert/jobs/{id}/result to getting result in form of application/pdf. After that job will be deleted.
There is two optiona to improve this: 
(a) deactivate automatic redirects on your browser / web client. Than you will see status response without be redirected to result endpoint
(b) I decided to refuse to remove job immediately after first result request. It will be deleted asynchronously based on timeout in the same way as failed job

**Comment by nirikash** [comment]
(b) will be implemented in #175

**Comment by grigoriev** [comment]
This behavior has been changed in v6.2.0
